domains/yii2copy/models/Auditorium.php
<?php
namespace app\models;
use yii\db\ActiveRecord;


class Auditorium extends ActiveRecord
{
}

?>

domains/yii2copy/models/Registration.php
<?php
namespace app\models;
use yii\base\Model;


class Registration extends Model
{
  public $phoneNumber;
  public $secretCode = 0;

  public function attributeLabels()
  {
    return[
      'phoneNumber' => 'Введите номер телефона',
      'secretCode' => 'Введите код из СМС',
    ];
  }

  public function rules()
  {
    return[
      ['phoneNumber', 'required'],
      ['secretCode', 'required'],
    ];
  }
}

?>

domains/yii2copy/models/Teacher.php
<?php
namespace app\models;
use yii\db\ActiveRecord;


class Teacher extends ActiveRecord
{
}

?>

domains/yii2copy/models/Test.php
<?php
namespace app\models;
use yii\db\ActiveRecord;


class Test extends ActiveRecord
{
}


?>

domains/yii2copy/models/TestForm.php
<?php
namespace app\models;
use yii\base\Model;


class TestForm extends Model
{
  public $DateTimeBegin;
  public $DateTimeEnd;
  public $Name;
  public $Teacher;
  public $Auditorium;
  public $Type;

  public function attributeLabels()
  {
    return[
      'DateTimeBegin' => 'Введите дату и время начала занятия',
      'DateTimeEnd' => 'Введите дату и время окончания занятия',
      'Name' => 'Введите название предмета',
      'Teacher' => 'Введите ФИО преподавателя',
      'Auditorium' => 'Введите аудиторию',
      'Type' => 'Введите тип занятия',
    ];
  }

  public function rules()
  {
    return[
      [['DateTimeBegin', 'DateTimeEnd'], 'safe'],
      ['Name', 'required'],
      ['Auditorium', 'required'],
      ['Teacher', 'required'],
      ['Type', 'number'],
    ];
  }
}

?>

domains/yii2copy/models/Timetable.php
<?php
namespace app\models;
use yii\db\ActiveRecord;


class Timetable extends ActiveRecord
{
  public static function tableName()
  {
    return 'Schedule';
  }
}

?>

domains/yii2copy/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\TestForm;
use Yii;
use yii\web\Controller;
use app\models\Timetable;
use app\models\Auditorium;
use app\models\Teacher;
use app\models\Registration;

require_once 'sms.ru.php';

class SiteController extends Controller
{
	//$code = 0;

	public function actionIndex()
	{
		$model = new TestForm();
		if ($model->load(Yii::$app->request->post()))
		{
			if ($model->validate()){
				$dts = explode(' ', $model->DateTimeBegin);
				$current_date = $dts[0];
				$searchingRecord1 = Timetable::find()->where(['<=', 'DateTimeBegin', $model->DateTimeBegin])
													 ->andWhere(['>=', 'DateTimeEnd', $model->DateTimeBegin])
													 ->andWhere(['Auditorium' => $model->Auditorium])
													 ->all();
				$searchingRecord2 = Timetable::find()->where(['<=', 'DateTimeBegin', $model->DateTimeEnd])
													 ->andWhere(['>=', 'DateTimeEnd', $model->DateTimeEnd])
													 ->andWhere(['Auditorium' => $model->Auditorium])
													 ->all();
				$searchingRecord3 = Timetable::find()->where(['>', 'DateTimeBegin', $model->DateTimeBegin])
													 ->andWhere(['<', 'DateTimeEnd', $model->DateTimeEnd])
													 ->andWhere(['Auditorium' => $model->Auditorium])
													 ->all();
				$searchingAudiorium = Auditorium::find()->where(['Name' => $model->Auditorium])->all();
				$searchingTeacher = Teacher::find()->where(['Name' => $model->Teacher])->all();
				$countRecords = count($searchingRecord1) + count($searchingRecord2) + count($searchingRecord3);
				if ($countRecords == 0 && count($searchingAudiorium) == 1 && count($searchingTeacher) == 1){
					Yii::$app->session->setFlash('success', 'Занятие добавлено в расписание!');
					$tempID = new Timetable();
					$tempID->DateTimeBegin = date($model->DateTimeBegin);
					$tempID->DateTimeEnd = date($model->DateTimeEnd);
					$tempID->Name = $model->Name;
					$tempID->Teacher = $model->Teacher;
					$tempID->Auditorium = $model->Auditorium;
					$tempID->Type = $model->Type;
					$tempID->save();
				}else{
					if (count($searchingAudiorium) == 0){
						Yii::$app->session->setFlash('error', 'Данной аудитории нет в списке!');
					}else {
						Yii::$app->session->setFlash('error', 'Аудитория занята!');
					}
					if (count($searchingTeacher) == 0){
						Yii::$app->session->setFlash('error', 'Данного преподавателя нет в списке!');
					}
				}

			}else{
				Yii::$app->session->setFlash('error', 'Данные некорректны');
			}

		}
		$date = Timetable::find()->where(['DATE(DateTimeBegin)' => $current_date])->all();
		//$leftDate = new DateTime(date($model->DateTimeBegin))
		//$data = Timetable::find()->where(['>', 'DateTimeBegin', date($model->DateTimeBegin) + strtotime('00:00:00'))])
			//											 ->andWhere(['<', 'DateTimeBegin', datetime(date($model->DateTimeBegin) + strtotime('23:59:59'))])->all();
		return $this->render('index', compact('model', 'date'));
	}

	public function actionAudit()
	{
			$data = Auditorium::find()->all();
			return $this->render('audit', compact('data'));
	}

	public function actionTeach()
	{
			$data = Teacher::find()->all();
			return $this->render('teach', compact('data'));
	}

	public function actionSender()
	{
		$model = new Registration();

		if ($model->load(Yii::$app->request->post()))
		{
				$number = $model->phoneNumber;

				$body = file_get_contents("https://sms.ru/sms/send?api_id=E511FBD0-FC67-5FF1-1893-8806473B2469&to=".$number."&msg=".urlencode($code)."&json=1");
				$json = json_decode($body);
				if ($model->secretCode == $code){
					Yii::$app->session->setFlash('success', 'Код верный!');
				}else {
					Yii::$app->session->setFlash('error', 'Код неверный!');
				}
		}
		return $this->render('sender', compact('model'));
	}

}
?>

domains/yii2copy/views/admin/user/index.php
<h1>LOL</h1>

domains/yii2copy/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Главная',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Редактирование расписания', 'url' => ['/site/index']],
            ['label' => 'Список аудиторий', 'url' => ['/site/audit']],
            ['label' => 'Список преподавателей', 'url' => ['/site/teach']],
            ['label' => 'Регистрация', 'url' => ['/site/sender']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

domains/yii2copy/views/site/audit.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Аудитории';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><b><?= Html::encode("Список аудиторий") ?></b></h1>
      <font size = 5>
        <?php foreach ($data as $d): ?>
          <li>
            <?= $d->Name ?>
          </li>
        <?php endforeach; ?>
      </font>

</div>

domains/yii2copy/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

domains/yii2copy/views/site/index.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<?php
 ?>




<?php $form = ActiveForm::begin() ?>
<?= $form->field($model, 'DateTimeBegin')->textInput(['style' => 'width:300px']); ?>
<?= $form->field($model, 'DateTimeEnd')->textInput(['style' => 'width:300px']); ?>
<?= $form->field($model, 'Name')->textInput(['style' => 'width:200px']); ?>
<?= $form->field($model, 'Teacher')->textInput(['style' => 'width:200px']); ?>
<?= $form->field($model, 'Auditorium')->textInput(['style' => 'width:200px']); ?>
<?= $form->field($model, 'Type')->textInput(['style' => 'width:100px']); ?>
<?= Html::submitButton('Добавить', ['class' => 'btn btn-success']) ?>
<?php ActiveForm::end() ?>

<h1><b><?= Html::encode("На этот день запланировано") ?></b></h1>
  <font size = 5>
    <?php foreach ($date as $d): ?>
      <li>
        <?php
          $dt1 = explode(' ', $d->DateTimeBegin);
          $dtHM = explode(':', $dt1[1]);
          $timeBeginH = $dtHM[0];
          $timeBeginM = $dtHM[1];
          $dt2 = explode(' ', $d->DateTimeEnd);
          $dtHM2 = explode(':', $dt2[1]);
          $timeEndH = $dtHM2[0];
          $timeEndM = $dtHM2[1];
        ?>
        <?= $timeBeginH.":".$timeBeginM."-".$timeEndH.":".$timeEndM." ".$d->Name." |   ".$d->Auditorium." | " ?>
      </li>
    <?php endforeach; ?>
  </font>

domains/yii2copy/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

domains/yii2copy/views/site/sender.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<?php
 ?>




<?php $form1 = ActiveForm::begin() ?>
<?= $form1->field($model, 'phoneNumber')->textInput(['style' => 'width:300px']); ?>
<?= Html::submitButton('Отправить СМС', ['class' => 'btn btn-success']) ?>
<?php ActiveForm::end() ?>
<?php $form2 = ActiveForm::begin() ?>
<?= $form2->field($model, 'secretCode')->textInput(['style' => 'width:300px']); ?>
<?= Html::submitButton('Подтвердить код', ['class' => 'btn btn-success']) ?>
<?php ActiveForm::end() ?>

<?php echo "Real code: ".$model->secretCode."  New code: ".$code ?>

domains/yii2copy/views/site/teach.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Преподаватели';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-teach">
    <h1><b><?= Html::encode("Список преподавателей") ?></b></h1>
      <font size = 5>
        <?php foreach ($data as $d): ?>
          <li>
            <?= $d->Name ?>
          </li>
        <?php endforeach; ?>
      </font>

</div>